### ISSUE TITLE
Neutral Registry / Helm Chart

### ISSUE THREAD

**Issue by rriverak** [Staffbase/syseleven-exporter#8]
Hey,
first of all, many thanks for this great Project. 
We are also a SysEleven Customers and looking for this kind of exporter.

At this point, thanks again for sharing this greate Solution.

We would like to use this container, but the image is in your private registry. 
Would a neutral Registry be more pleasant for you? (e.g. DockerHub)

We would also like to provide the container as a Helm Chart. 
If there is no chart for this yet, we would be happy to contribute.

I look forward to your reply.

best regards,

Ricardo

**Comment by axdotl** [comment]
Hello Ricardo,

thanks for your request. We will discuss this internally.
I keep you posted.

**Comment by ricoberger** [comment]
Hi @rriverak, the exporter is now available at Docker Hub: https://hub.docker.com/repository/docker/staffbace/syseleven-exporter

@mechko is currently working on the CLA process, with our legal department, so that we can accept contributions for this repository.

**Comment by rriverak** [comment]
Hey @ricoberger, @axdotl 
thanks a lot for this! 😃 
I am very excited about your professional approach! ❤️ 

best regards,

Ricardo

**Comment by rriverak** [comment]
Hey,
in the meantime we have created a Helm Chart. 
https://github.com/vfm/syseleven-exporter-chart/

I'm not sure if a Helm Chart and a Container Image are possible in a single Github Repository.
We could also leave it with two Repositories and mention each other.

best regards,

Ricardo

**Comment by ricoberger** [comment]
Hi @rriverak, thank you for providing a Helm chart for the exporter.

We also have added a link to your repository.
